{{- if and (not .Values.postgresql.external) .Values.postgresql.storage.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "sentinel.fullname" . }}-postgresql
  labels:
    {{- include "sentinel.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.postgresql.storage.size }}
  {{- if .Values.postgresql.storage.storageClass }}
  storageClassName: {{ .Values.postgresql.storage.storageClass | quote }}
  {{- end }}
{{- end }}