apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sentinel.fullname" . }}-db
  labels:
    {{- include "sentinel.labels" . | nindent 4 }}
type: Opaque
{{- $secretName := printf "%s-db" (include "sentinel.fullname" .) -}}
{{- $existing := (lookup "v1" "Secret" .Release.Namespace $secretName) -}}
{{- $existingDBPassword := "" -}}
{{- $existingAuthToken := "" -}}
{{- if $existing }}
  {{- with (index $existing.data "DB_PASSWORD") }}
    {{- $existingDBPassword = (. | b64dec) -}}
  {{- end }}
  {{- with (index $existing.data "AUTH_TOKEN") }}
    {{- $existingAuthToken = (. | b64dec) -}}
  {{- end }}
{{- end }}

{{- $dbPassword := .Values.database.password -}}
{{- if not $dbPassword }}
  {{- if $existingDBPassword }}
    {{- $dbPassword = $existingDBPassword -}}
  {{- else }}
    {{- $dbPassword = randAlphaNum 32 -}}
  {{- end }}
{{- end }}

{{- $authToken := .Values.agent.auth.token -}}
{{- if .Values.agent.auth.enabled }}
  {{- if not $authToken }}
    {{- if $existingAuthToken }}
      {{- $authToken = $existingAuthToken -}}
    {{- else }}
      {{- $authToken = randAlphaNum 64 -}}
    {{- end }}
  {{- end }}
{{- end }}
stringData:
  DB_USER: {{ .Values.database.user | quote }}
  DB_PASSWORD: {{ $dbPassword | quote }}
  DB_NAME: {{ .Values.database.name | quote }}
  DB_HOST: {{ include "sentinel.postgresHost" . | quote }}
  DB_SSLMODE: {{ .Values.database.sslmode | quote }}
  {{- if .Values.agent.auth.enabled }}
  AUTH_TOKEN: {{ $authToken | quote }}
  {{- end }}
